name: Sync to Hugging Face Hub (LFS Fixed)

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Migrate keras model to Git LFS (HISTORY FIX)
        run: |
          git lfs migrate import --include="*.keras"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://Barshan2004:$HF_TOKEN@huggingface.co/spaces/Barshan2004/AB main
